language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libssl-dev libmysqlclient-dev libgtest-dev libboost-all-dev libz-dev; fi


script:
  - ./bootstrap.py
  - ./waf configure
  - ./waf build

branches:
  only:
    - master

notifications:
  email: false

env:
  - LANG="en_US.UTF-8"

os:
  - linux

