language: cpp

compiler:
  - gcc
  - clang

env:
  global:
    - GCC_VERSION="4.8"
    
before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y llvm-3.4 llvm-3.4-dev
  - sudo apt-get install -y libssl-dev libmysqlclient-dev libgtest-dev libboost-all-dev libz-dev

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq "g++-${GCC_VERSION}"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq "libstdc++-${GCC_VERSION}-dev"; fi
  
script:
  - ./bootstrap.py
  - ./waf configure
  - ./waf build

branches:
  only:
    - master

notifications:
  email: false

env:
  - LANG="en_US.UTF-8"

os:
  - linux

